version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env.frontend
    ports:
      - '8100:8000'
    volumes:
      - pelmen-frontend-dist:/app/dist

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - pelmen-frontend-dist:/usr/share/nginx/html
      - certs:/etc/letsencrypt
    ports:
      - '80:80'     # HTTP для редиректа или валидации (если понадобится)
      - '443:443'   # HTTPS (незаменимый порт для вашего случая)
    depends_on:
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - certs:/etc/letsencrypt
    # Пример команды для DNS challenge (необходим ручной ввод или автоматизация через DNS API)
    command: >
      certonly --manual
              --preferred-challenges dns
              -d krolpluskrosh.online
              --agree-tos --no-eff-email
              --manual-public-ip-logging-ok

volumes:
  pelmen-frontend-dist:
  certs:
