version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - .env.frontend
    ports:
      - '8100:8000'
    volumes:
      - pelmen-frontend-dist:/app/dist

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - pelmen-frontend-dist:/usr/share/nginx/html
      - ./nginx/ssl:/etc/nginx/certs
    ports:
      - '80:80'
    depends_on:
      - frontend

volumes:
  pelmen-frontend-dist: